# TODO: Check the default values handling
# Admin layout
layout: 'lcms/engine/admin'

# TODO: Check the default values handling
# Engine
engine: 'Lcms::Engine::Engine'

# TODO: Check the default values handling
# Redirects
redirect:
  host:
    # TODO: Check the handle of chained path here
    root_path: 'admin_path'
  engine:
    # TODO: Check the handle of chained path here
    document_path: 'document_path'
    # TODO: Check the handle of chained path here
    material_path: 'material_path'

# TODO: Check the default values handling
# Redefine views
documents:
  index: '/lcms/engine/admin/documents/index'
  view_links:
    - '/documents/:id'

# TODO: Check the default values handling
materials:
  index: '/lcms/engine/admin/materials/index'
  view_links:
    - '/materials/:id'
